package pencil_utensil.organaut.network.sse;

public enum BroadcastEvent {
	ADDRESS_CREATED,
	COORDINATES_CREATED,
	ORGANIZATION_CREATED,
	ORGANIZATION_DELETED,
	ORGANIZATIONS_DELETED,
	ORGANIZATION_UPDATED;

}
